### PR TITLE
README.md: Add instruction to run webpack

### PR DESCRIPTION
**Pull request by ockham**

### CODE REVIEW

**Comment by tlovett1** [comment]
This should happen on `npm install`:

https://github.com/10up/twentysixteenreact/blob/master/package.json#L25

Maybe Composer didn't pull in the latest version?

**Comment by ockham** [comment]
Hmm, looks like it. I don't have that in my package.json.

`git status` inside `twentysixteenreact` says

> Your branch is behind 'origin/master' by 7 commits, and can be fast-forwarded.

**Comment by ockham** [comment]
Fine to close in that case, I guess.

**Comment by tlovett1** [comment]
What happens if you clear composer cache and update?

**Comment by ockham** [comment]
Hmm, that still pulls an outdated commit:

> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 1 install, 0 updates, 0 removals
>  - Installing 10up/twentysixteenreact (dev-master 23d76a1) Cloning 23d76a11c3 from cache

`git status`:
> Your branch is behind 'origin/master' by 8 commits, and can be fast-forwarded.

I also tried removing `composer.lock` -- same result :-/

**Comment by tlovett1** [comment]
Should be fixed now. Thanks!

**Pull request closed without merging**
